# Generated by Django 5.0.6 on 2024-07-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('legId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('destinationAirport', models.CharField(max_length=100)),
                ('totalFare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('segmentsArrivalTimeEpochSeconds', models.IntegerField()),
                ('segmentsDepartureTimeEpochSeconds', models.IntegerField()),
                ('segmentsArrivalAirportCode', models.CharField(max_length=100)),
                ('segmentsDepartureAirportCode', models.CharField(max_length=100)),
                ('segmentsAirlineName', models.CharField(max_length=100)),
            ],
        ),
    ]
