# Generated by Django 5.0.6 on 2024-07-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('total_stops', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('dep_hours', models.IntegerField()),
                ('dep_min', models.IntegerField()),
                ('arrival_hours', models.IntegerField()),
                ('arrival_min', models.IntegerField()),
                ('duration_hours', models.IntegerField()),
                ('duration_min', models.IntegerField()),
            ],
        ),
    ]
