# Generated by Django 5.0.6 on 2024-07-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='legIdBack',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
    ]
