# Generated by Django 5.0.6 on 2024-07-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_flight_legidback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='totalFare',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
    ]
